### ISSUE TITLE
Unable to add stock 

### ISSUE THREAD

**Issue by farouqzakwan** [jainsamyak/Stockifier#1]
Found your apps in electron apps list.Test using windows 10

1. click on add stock button
2. search for takaful
3. choose Syarikat Takaful Malaysia Bhd (6139.KLA)
4. click on proceed and nothing happen

**Comment by jainsamyak** [comment]
> Found your apps in electron apps list.Test using windows 10
> 
> 1. click on add stock button
> 2. search for takaful
> 3. choose Syarikat Takaful Malaysia Bhd (6139.KLA)
> 4. click on proceed and nothing happen

Hi farouqzakwan!
Thanks for your interest in Stockifier. Your issue is most likely due to the Alphavantage API exceeding it’s limit. The API can handle 5 requests per minute only. I suggest that if possible you opt for the premium key that has a higher limit or just wait for a few seconds after the stock appears in the list before clicking Add Stock.

Thanks.

**Comment by dwk81022** [comment]
### _``_
